In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.11.0'

# part 1 preparing data
import dataset

In [28]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


label encoding binary variable gender

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
X.dtype

dtype('O')

One Hot Encode categorical feature

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Train test split

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [32]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

feature scaling 

In [33]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# part 2 building ann
initializing ann

In [34]:
ann = tf.keras.Sequential()

In [35]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [36]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [37]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

training ann

In [38]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'] )

In [19]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5776 - accuracy: 0.7801
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4712 - accuracy: 0.7990
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4479 - accuracy: 0.8031
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4378 - accuracy: 0.8076
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4330 - accuracy: 0.8101
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4300 - accuracy: 0.8126
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4276 - accuracy: 0.8121
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4253 - accuracy: 0.8134
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4240 - accuracy: 0.8161
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4226 - accura

In [39]:
'''
Homework:
Use our ANN model to predict if the customer with the following informations will leave the bank: 
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer?
'''

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 [==============================] - 0s 101ms/step


array([[0.47246605]], dtype=float32)

#part 3 evaluating model
testing of model

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)